## Part 1: Explore the Data

Import the data and use Pandas to learn more about the dataset.

In [3]:
import pandas as pd

pandas_challenge_df = pd.read_csv('Resources/client_dataset.csv')
pandas_challenge_df.head()

first      last                    job               phone  \
0     Donald   Harding           Immunologist  793-904-7725x39308   
1    Tiffany     Myers        Music therapist    201.442.4543x942   
2    Shannon    Watson           Immunologist   687.737.9424x8503   
3     Nathan     Baker  Accounting technician    827-788-8123x012   
4  Christina  Schwartz           Chiropractor        265-829-3643   

                                 email  client_id  order_id  order_date  \
0     harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1    myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                swatson8146@payne.net      57113   1902144  2023-01-29   
3               bakernathan@benson.com      46554   9031802  2023-04-25   
4  christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   

   order_week  order_year         item_id     category         subcategory  \
0          17        2023  EUD29711-63-6U        decor            wall art   
1          20        2023  XDA18116-89-4A  consumables                pens   
2           4        2023  ABE59463-05-7E     software  project management   
3          17        2023  ZMM00836-65-0C  consumables                pens   
4          21        2023  BZX55559-12-3X  consumables                misc   

   unit_price  unit_cost  unit_weight  qty  line_number  
0     1096.80     762.71         7.50  105            1  
1       24.95      15.09         1.49   21            0  
2       13.52       7.86         1.68   39            6  
3       36.42      24.85         1.23   29            3  
4      195.10     108.17        46.43   20            1

In [4]:
# View the column names in the data
pandas_challenge_df.columns

Index(['first', 'last', 'job', 'phone', 'email', 'client_id', 'order_id',
       'order_date', 'order_week', 'order_year', 'item_id', 'category',
       'subcategory', 'unit_price', 'unit_cost', 'unit_weight', 'qty',
       'line_number'],
      dtype='object')

In [5]:
# Use the describe function to gather some basic statistics
pandas_challenge_df.describe()


client_id      order_id    order_week    order_year    unit_price  \
count  54639.000000  5.463900e+04  54639.000000  54639.000000  54639.000000   
mean   54837.869416  5.470190e+06     11.359139   2022.993064    136.267207   
std    25487.438231  2.599807e+06      7.023499      0.082997    183.873135   
min    10033.000000  1.000886e+06      1.000000   2022.000000      0.010000   
25%    33593.000000  3.196372e+06      6.000000   2023.000000     20.800000   
50%    53305.000000  5.496966e+06     11.000000   2023.000000     68.310000   
75%    78498.000000  7.733869e+06     17.000000   2023.000000    173.160000   
max    99984.000000  9.998480e+06     52.000000   2023.000000   1396.230000   

          unit_cost   unit_weight           qty   line_number  
count  54639.000000  54639.000000  5.463900e+04  54639.000000  
mean      99.446073      5.004116  5.702646e+02      2.979667  
std      133.164267      5.326599  1.879552e+04      2.436320  
min        0.010000      0.000000  0.000000e+00      0.000000  
25%       14.840000      1.450000  3.200000e+01      1.000000  
50%       49.890000      3.240000  6.800000e+01      3.000000  
75%      125.570000      6.890000  1.700000e+02      5.000000  
max      846.270000     46.430000  3.958244e+06      9.000000

In [6]:
# Use this space to do any additional research
# and familiarize yourself with the data.
pandas_challenge_df.dtypes


first           object
last            object
job             object
phone           object
email           object
client_id        int64
order_id         int64
order_date      object
order_week       int64
order_year       int64
item_id         object
category        object
subcategory     object
unit_price     float64
unit_cost      float64
unit_weight    float64
qty              int64
line_number      int64
dtype: object

In [7]:
pandas_challenge_df.count()

first          54639
last           54639
job            54639
phone          54639
email          54639
client_id      54639
order_id       54639
order_date     54639
order_week     54639
order_year     54639
item_id        54639
category       54639
subcategory    54639
unit_price     54639
unit_cost      54639
unit_weight    54639
qty            54639
line_number    54639
dtype: int64

In [8]:
pandas_challenge_df.isnull().sum()

first          0
last           0
job            0
phone          0
email          0
client_id      0
order_id       0
order_date     0
order_week     0
order_year     0
item_id        0
category       0
subcategory    0
unit_price     0
unit_cost      0
unit_weight    0
qty            0
line_number    0
dtype: int64

In [9]:
pandas_challenge_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54639 entries, 0 to 54638
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   first        54639 non-null  object 
 1   last         54639 non-null  object 
 2   job          54639 non-null  object 
 3   phone        54639 non-null  object 
 4   email        54639 non-null  object 
 5   client_id    54639 non-null  int64  
 6   order_id     54639 non-null  int64  
 7   order_date   54639 non-null  object 
 8   order_week   54639 non-null  int64  
 9   order_year   54639 non-null  int64  
 10  item_id      54639 non-null  object 
 11  category     54639 non-null  object 
 12  subcategory  54639 non-null  object 
 13  unit_price   54639 non-null  float64
 14  unit_cost    54639 non-null  float64
 15  unit_weight  54639 non-null  float64
 16  qty          54639 non-null  int64  
 17  line_number  54639 non-null  int64  
dtypes: float64(3), int64(6), object(9)
memory usag

In [10]:
pandas_challenge_df.min()

first                             Aaron
last                             Abbott
job               Accommodation manager
phone                     (203)310-1717
email          a.garcia.3072@durham.com
client_id                         10033
order_id                        1000886
order_date                   2023-01-01
order_week                            1
order_year                         2022
item_id                  AAD15703-65-3A
category                    consumables
subcategory                  accounting
unit_price                         0.01
unit_cost                          0.01
unit_weight                         0.0
qty                                   0
line_number                           0
dtype: object

In [11]:
pandas_challenge_df.max()

first                              Zachary
last                                Zavala
job                           Youth worker
phone                    999.801.2159x2255
email          zacharyjohnson@jacobson.net
client_id                            99984
order_id                           9998480
order_date                      2023-05-30
order_week                              52
order_year                            2023
item_id                     ZZU43604-44-9M
category                          software
subcategory                       wall art
unit_price                         1396.23
unit_cost                           846.27
unit_weight                          46.43
qty                                3958244
line_number                              9
dtype: object

In [12]:
pandas_challenge_df['client_id'].unique()

array([58515, 37609, 57113, 46554, 92089, 33615, 87213, 46709, 73362,
       58789, 81012, 74112, 18145, 48855, 67407, 26185, 17355, 28523,
       77184, 61603, 51869, 85413, 74159, 33804, 54932, 87125, 10643,
       10351, 10559, 31733, 95847, 97623, 68703, 28927, 48015, 90654,
       67516, 75118, 32185, 96736, 89499, 79827, 45569, 61647, 53409,
       17002, 18349, 25936, 37715, 41908, 25397, 59472, 77583, 34507,
       17697, 33956, 56645, 42481, 28011, 21654, 43361, 73729, 32597,
       34878, 24053, 48148, 27983, 55398, 40622, 41766, 40677, 92169,
       74058, 79361, 31268, 34313, 95108, 34706, 70043, 12286, 76087,
       99043, 28331, 47644, 13436, 31165, 79451, 22890, 14180, 32098,
       71958, 56590, 84527, 38220, 19206, 91091, 14312, 75546, 57762,
       10520, 86810, 31715, 65049, 87506, 22670, 49058, 82075, 37608,
       96954, 53348, 40490, 97794, 22008, 77340, 47507, 86045, 99231,
       49037, 19820, 61465, 48193, 32620, 14935, 16444, 37542, 46820,
       16500, 65084,

In [13]:
pandas_challenge_df['client_id'].nunique()

999

In [14]:
pandas_challenge_df['item_id'].unique()

array(['EUD29711-63-6U', 'XDA18116-89-4A', 'ABE59463-05-7E',
       'ZMM00836-65-0C', 'BZX55559-12-3X', 'BMB23158-88-9A',
       'UAC50632-25-4E', 'UEU25316-01-1U', 'DDA06248-98-7Z',
       'DUU85042-87-5E', 'DCD61783-36-6B', 'ZAE56533-39-8U',
       'BDC65078-60-7M', 'AME10969-48-7D', 'BXM59071-01-6D',
       'CCX95657-71-3B', 'ZEA01443-18-5A', 'CUU90642-03-7C',
       'UCX86104-19-0Z', 'ZDX29223-32-0B', 'ZAU36048-03-9A',
       'EZX36378-17-7A', 'UAU40137-77-3U', 'ZMB00381-41-4E',
       'XZZ76042-95-6X', 'BAD54487-56-3C', 'UZZ84388-36-3B',
       'DBE42716-07-1U', 'UMC49136-12-1E', 'EDU54097-48-4E',
       'MAU13971-98-9B', 'ZEZ40347-39-4X', 'UUE15482-56-0X',
       'CCA32097-88-6M', 'AEE51706-20-3U', 'DZX13514-89-1M',
       'CZC97008-29-8E', 'AEM31850-24-5M', 'MDB11336-71-2E',
       'XAU13501-34-9A', 'CBZ89457-17-5C', 'AED36322-86-8U',
       'AZB92583-19-5D', 'DXU77211-79-0B', 'EUX51497-34-6B',
       'AEE37351-26-7B', 'XBM94536-93-1U', 'AUZ65769-43-0D',
       'EBB79610-74-2A',

In [15]:
pandas_challenge_df['item_id'].nunique()

500

In [16]:
pandas_challenge_df['category'].unique()

array(['decor', 'consumables', 'software', 'furniture', 'electronics'],
      dtype=object)

In [17]:
# What three item categories had the most entries?
most_entries = pandas_challenge_df['category'].value_counts().head(3)
print(most_entries)

category
consumables    23538
furniture      11915
software        8400
Name: count, dtype: int64


In [18]:
pandas_challenge_df['subcategory'].unique()

array(['wall art', 'pens', 'project management', 'misc', 'plants',
       'kitchen supplies', 'paper products', 'seating', 'computers',
       'stands', 'tables', 'bathroom supplies', 'audio visual',
       'accounting', 'logistics', 'telecom', 'desks', 'cabling'],
      dtype=object)

In [19]:
pandas_challenge_df['subcategory'].value_counts()

subcategory
bathroom supplies     6424
paper products        5874
kitchen supplies      5746
tables                4540
misc                  4286
stands                4201
accounting            3756
project management    3522
plants                3466
wall art              3093
seating               2664
pens                  2603
logistics             1122
telecom                978
audio visual           732
cabling                655
desks                  510
computers              467
Name: count, dtype: int64

In [20]:
# For the category with the most entries, which subcategory had the most entries?
subcategory_counts = pandas_challenge_df.groupby(['category', 'subcategory']).size().reset_index(name='counts')
print(subcategory_counts)

       category         subcategory  counts
0   consumables   bathroom supplies    6424
1   consumables    kitchen supplies    5746
2   consumables                misc    2891
3   consumables      paper products    5874
4   consumables                pens    2603
5         decor                misc    1395
6         decor              plants    3466
7         decor            wall art    3093
8   electronics        audio visual     732
9   electronics             cabling     655
10  electronics           computers     467
11  electronics             telecom     978
12    furniture               desks     510
13    furniture             seating    2664
14    furniture              stands    4201
15    furniture              tables    4540
16     software          accounting    3756
17     software           logistics    1122
18     software  project management    3522


In [21]:
print(subcategory_counts.iloc[0])

category             consumables
subcategory    bathroom supplies
counts                      6424
Name: 0, dtype: object


In [22]:
# ChatGPT Alternative
most_category = pandas_challenge_df['category'].value_counts().idxmax()
most_category_df = pandas_challenge_df[pandas_challenge_df['category'] == most_category]
most_subcategory_count = most_category_df['subcategory'].value_counts().idxmax()
print(most_subcategory_count, most_category_df['subcategory'].value_counts().max())


bathroom supplies 6424


In [23]:
# Which five clients had the most entries in the data?
most_client_id = pandas_challenge_df['client_id'].value_counts()
print(most_client_id.head())

client_id
33615    220
66037    211
46820    209
38378    207
24741    207
Name: count, dtype: int64


In [24]:
# Store the client ids of those top 5 clients in a list.
top5_client_id = most_client_id.head().index.tolist()
print(top5_client_id)

[33615, 66037, 46820, 38378, 24741]


In [26]:
# How many total units (the qty column) did the client with the most entries order order?
top_client_orders_df = pandas_challenge_df[pandas_challenge_df['client_id'] == 33615]
total_units_ordered = top_client_orders_df['qty'].sum()
print(f"Total units: {total_units_ordered}")

Total units: 64313


## Part 2: Transform the Data
Do we know that this client spent the more money than client 66037? If not, how would we find out? Transform the data using the steps below to prepare it for analysis.

In [27]:
# Create a column that calculates the subtotal for each line using the unit_price and the qty
pandas_challenge_df['subtotal'] = pandas_challenge_df['qty'] * pandas_challenge_df['unit_price']
pandas_challenge_df.columns

Index(['first', 'last', 'job', 'phone', 'email', 'client_id', 'order_id',
       'order_date', 'order_week', 'order_year', 'item_id', 'category',
       'subcategory', 'unit_price', 'unit_cost', 'unit_weight', 'qty',
       'line_number', 'subtotal'],
      dtype='object')

In [28]:
pandas_challenge_df['shipping_weight'] = pandas_challenge_df['qty'] * pandas_challenge_df['unit_weight']

In [29]:
# Create a column for shipping price.
# Assume a shipping price of $7 per pound for orders over 50 pounds and $10 per pound for items 50 pounds or under.
def calc_shipping_price(shipping_weight):
    if shipping_weight > 50:
        return shipping_weight * 7 
    else:
        return shipping_weight * 10
pandas_challenge_df['total_shipping_price'] = pandas_challenge_df ['shipping_weight'].apply(calc_shipping_price)
pandas_challenge_df.columns
pandas_challenge_df.head()

first      last                    job               phone  \
0     Donald   Harding           Immunologist  793-904-7725x39308   
1    Tiffany     Myers        Music therapist    201.442.4543x942   
2    Shannon    Watson           Immunologist   687.737.9424x8503   
3     Nathan     Baker  Accounting technician    827-788-8123x012   
4  Christina  Schwartz           Chiropractor        265-829-3643   

                                 email  client_id  order_id  order_date  \
0     harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1    myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                swatson8146@payne.net      57113   1902144  2023-01-29   
3               bakernathan@benson.com      46554   9031802  2023-04-25   
4  christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   

   order_week  order_year  ...     category         subcategory unit_price  \
0          17        2023  ...        decor            wall art    1096.80   
1          20        2023  ...  consumables                pens      24.95   
2           4        2023  ...     software  project management      13.52   
3          17        2023  ...  consumables                pens      36.42   
4          21        2023  ...  consumables                misc     195.10   

   unit_cost  unit_weight  qty  line_number   subtotal  shipping_weight  \
0     762.71         7.50  105            1  115164.00           787.50   
1      15.09         1.49   21            0     523.95            31.29   
2       7.86         1.68   39            6     527.28            65.52   
3      24.85         1.23   29            3    1056.18            35.67   
4     108.17        46.43   20            1    3902.00           928.60   

   total_shipping_price  
0               5512.50  
1                312.90  
2                458.64  
3                356.70  
4               6500.20  

[5 rows x 21 columns]

In [30]:
# Create a column for the total price using the subtotal and the shipping price along with a sales tax of 9.25%
pandas_challenge_df['total_price'] = (pandas_challenge_df['subtotal'] + pandas_challenge_df['total_shipping_price']) * 1.0925
pandas_challenge_df.columns
pandas_challenge_df.head()

first      last                    job               phone  \
0     Donald   Harding           Immunologist  793-904-7725x39308   
1    Tiffany     Myers        Music therapist    201.442.4543x942   
2    Shannon    Watson           Immunologist   687.737.9424x8503   
3     Nathan     Baker  Accounting technician    827-788-8123x012   
4  Christina  Schwartz           Chiropractor        265-829-3643   

                                 email  client_id  order_id  order_date  \
0     harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1    myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                swatson8146@payne.net      57113   1902144  2023-01-29   
3               bakernathan@benson.com      46554   9031802  2023-04-25   
4  christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   

   order_week  order_year  ...         subcategory unit_price unit_cost  \
0          17        2023  ...            wall art    1096.80    762.71   
1          20        2023  ...                pens      24.95     15.09   
2           4        2023  ...  project management      13.52      7.86   
3          17        2023  ...                pens      36.42     24.85   
4          21        2023  ...                misc     195.10    108.17   

   unit_weight  qty  line_number   subtotal  shipping_weight  \
0         7.50  105            1  115164.00           787.50   
1         1.49   21            0     523.95            31.29   
2         1.68   39            6     527.28            65.52   
3         1.23   29            3    1056.18            35.67   
4        46.43   20            1    3902.00           928.60   

   total_shipping_price    total_price  
0               5512.50  131839.076250  
1                312.90     914.258625  
2                458.64    1077.117600  
3                356.70    1543.571400  
4               6500.20   11364.403500  

[5 rows x 22 columns]

In [31]:
# Create a column for the cost of each line using unit cost, qty, and
# shipping price (assume the shipping cost is exactly what is charged to the client).

pandas_challenge_df['line_cost'] = (pandas_challenge_df['unit_cost'] * pandas_challenge_df ['qty']) + pandas_challenge_df ['total_shipping_price']
pandas_challenge_df.columns
pandas_challenge_df.head()

first      last                    job               phone  \
0     Donald   Harding           Immunologist  793-904-7725x39308   
1    Tiffany     Myers        Music therapist    201.442.4543x942   
2    Shannon    Watson           Immunologist   687.737.9424x8503   
3     Nathan     Baker  Accounting technician    827-788-8123x012   
4  Christina  Schwartz           Chiropractor        265-829-3643   

                                 email  client_id  order_id  order_date  \
0     harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1    myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                swatson8146@payne.net      57113   1902144  2023-01-29   
3               bakernathan@benson.com      46554   9031802  2023-04-25   
4  christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   

   order_week  order_year  ... unit_price unit_cost unit_weight  qty  \
0          17        2023  ...    1096.80    762.71        7.50  105   
1          20        2023  ...      24.95     15.09        1.49   21   
2           4        2023  ...      13.52      7.86        1.68   39   
3          17        2023  ...      36.42     24.85        1.23   29   
4          21        2023  ...     195.10    108.17       46.43   20   

   line_number   subtotal  shipping_weight  total_shipping_price  \
0            1  115164.00           787.50               5512.50   
1            0     523.95            31.29                312.90   
2            6     527.28            65.52                458.64   
3            3    1056.18            35.67                356.70   
4            1    3902.00           928.60               6500.20   

     total_price  line_cost  
0  131839.076250   85597.05  
1     914.258625     629.79  
2    1077.117600     765.18  
3    1543.571400    1077.35  
4   11364.403500    8663.60  

[5 rows x 23 columns]

In [32]:
# Create a column for the profit of each line using line cost and line price

pandas_challenge_df['profit'] = pandas_challenge_df['total_price'] - pandas_challenge_df ['line_cost']
pandas_challenge_df.columns
pandas_challenge_df.head()

first      last                    job               phone  \
0     Donald   Harding           Immunologist  793-904-7725x39308   
1    Tiffany     Myers        Music therapist    201.442.4543x942   
2    Shannon    Watson           Immunologist   687.737.9424x8503   
3     Nathan     Baker  Accounting technician    827-788-8123x012   
4  Christina  Schwartz           Chiropractor        265-829-3643   

                                 email  client_id  order_id  order_date  \
0     harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1    myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                swatson8146@payne.net      57113   1902144  2023-01-29   
3               bakernathan@benson.com      46554   9031802  2023-04-25   
4  christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   

   order_week  order_year  ... unit_cost unit_weight  qty  line_number  \
0          17        2023  ...    762.71        7.50  105            1   
1          20        2023  ...     15.09        1.49   21            0   
2           4        2023  ...      7.86        1.68   39            6   
3          17        2023  ...     24.85        1.23   29            3   
4          21        2023  ...    108.17       46.43   20            1   

    subtotal  shipping_weight  total_shipping_price    total_price  line_cost  \
0  115164.00           787.50               5512.50  131839.076250   85597.05   
1     523.95            31.29                312.90     914.258625     629.79   
2     527.28            65.52                458.64    1077.117600     765.18   
3    1056.18            35.67                356.70    1543.571400    1077.35   
4    3902.00           928.60               6500.20   11364.403500    8663.60   

         profit  
0  46242.026250  
1    284.468625  
2    311.937600  
3    466.221400  
4   2700.803500  

[5 rows x 24 columns]

## Part 3: Confirm your work
You have email receipts showing that the total prices for 3 orders. Confirm that your calculations match the receipts. Remember, each order has multiple lines.

Order ID 2742071 had a total price of \$152,811.89

Order ID 2173913 had a total price of \$162,388.71

Order ID 6128929 had a total price of \$923,441.25


In [33]:
# Check your work using the totals above
order_id_check_1 = 2742071
order_id_check_1_df = pandas_challenge_df[pandas_challenge_df['order_id'] == order_id_check_1]
total_order_id_check_1 = order_id_check_1_df['total_price'].sum()
print(f"{total_order_id_check_1:.2f}")

152811.90


In [34]:
# Check your work using the totals above
order_id_check_1 = 2173913
order_id_check_1_df = pandas_challenge_df[pandas_challenge_df['order_id'] == order_id_check_1]
total_order_id_check_1 = order_id_check_1_df['total_price'].sum()
print(f"{total_order_id_check_1:.2f}")

162388.72


In [35]:
order_id_check_1 = 6128929
order_id_check_1_df = pandas_challenge_df[pandas_challenge_df['order_id'] == order_id_check_1]
total_order_id_check_1 = order_id_check_1_df['total_price'].sum()
print(f"{total_order_id_check_1:.2f}")

923441.24


## Part 4: Summarize and Analyze
Use the new columns with confirmed values to find the following information.

In [50]:
# How much did each of the top 5 clients by quantity spend? Check your work from Part 1 for client ids.
top5_client_ids = [33615, 66037, 46820, 38378, 24741]
top5_clients_df = pandas_challenge_df[pandas_challenge_df['client_id'].isin(top5_client_ids )]
top5_clients_spending = top5_clients_df.groupby('client_id')['total_price'].sum().round(2)
print(top5_clients_spending)

client_id
24741    82268891.98
33615     8377308.57
38378    12906550.88
46820     9743794.32
66037    10259514.80
Name: total_price, dtype: float64


In [88]:
# Create a summary DataFrame showing the totals for the for the top 5 clients with the following information:
# total units purchased, total shipping price, total revenue, and total profit. 
# Assuming top5_client_ids contains the IDs of the top 5 clients
top5_clients_summary_df = pandas_challenge_df[pandas_challenge_df['client_id'].isin(top5_client_ids)]

top5_clients_summary_df = top5_clients_summary_df.groupby('client_id').agg({
    'qty': 'sum',  # total units purchased
    'total_shipping_price': 'sum',
    'total_price': 'sum',  # total revenue
    'profit': 'sum'  # total profit
}).reset_index()

# Rename the columns for clarity
top5_clients_summary = top5_clients_summary.rename(columns={
    'qty': 'Total Units Purchased',
    'total_shipping_price': 'Total Shipping Price',
    'total_price': 'Total Revenue',
    'profit': 'Total Profit'
})

# Display the summary DataFrame
top5_clients_summary_df




client_id     qty  total_shipping_price   total_price        profit
0      24741  239862            5126448.37  8.226889e+07  3.657999e+07
1      33615   64313            1828984.89  8.377309e+06  2.201995e+06
2      38378   73667            3429455.40  1.290655e+07  3.271830e+06
3      46820   75768            1601448.84  9.743794e+06  2.736603e+06
4      66037   43018            1395151.85  1.025951e+07  3.255032e+06

In [89]:
# Define the money columns
money_columns = ['total_shipping_price', 'total_price', 'profit']

# Define a function to convert a dollar amount to millions
def convert_to_millions(amount):
    return '${:.6f}'.format(amount / 1000000)

# Apply the conversion function to the money columns
for col in money_columns:
    top5_clients_summary_df[col] = top5_clients_summary_df[col].apply(convert_to_millions)

# Rename the columns to reflect the change in the money format
top5_clients_summary_df = top5_clients_summary_df.rename(columns={
    'client_id': 'Client ID',
    'qty': 'Units',
    'total_shipping_price': 'Shipping (millions)',
    'total_price': 'Total Revenue (millions)',
    'profit': 'Total Profit (millions)'
})

# Display the formatted DataFrame
top5_clients_summary_df


Client ID   Units Shipping (millions) Total Revenue (millions)  \
0      24741  239862           $5.126448               $82.268892   
1      33615   64313           $1.828985                $8.377309   
2      38378   73667           $3.429455               $12.906551   
3      46820   75768           $1.601449                $9.743794   
4      66037   43018           $1.395152               $10.259515   

  Total Profit (millions)  
0              $36.579992  
1               $2.201995  
2               $3.271830  
3               $2.736603  
4               $3.255032

In [91]:

top5_clients_summary_df = top5_clients_summary_df.sort_values(by='Total Profit (millions)', ascending=False)
top5_clients_summary_df

Client ID   Units Shipping (millions) Total Revenue (millions)  \
0      24741  239862           $5.126448               $82.268892   
2      38378   73667           $3.429455               $12.906551   
4      66037   43018           $1.395152               $10.259515   
3      46820   75768           $1.601449                $9.743794   
1      33615   64313           $1.828985                $8.377309   

  Total Profit (millions)  
0              $36.579992  
2               $3.271830  
4               $3.255032  
3               $2.736603  
1               $2.201995

In [96]:
# Convert the columns to numeric values
top5_clients_summary_df['Shipping (millions)'] = top5_clients_summary_df['Shipping (millions)'].str.replace('$', '').str.replace('M', '').astype(float)
top5_clients_summary_df['Total Revenue (millions)'] = top5_clients_summary_df['Total Revenue (millions)'].str.replace('$', '').str.replace('M', '').astype(float)
top5_clients_summary_df['Total Profit (millions)'] = top5_clients_summary_df['Total Profit (millions)'].str.replace('$', '').str.replace('M', '').astype(float)

# Apply the formatting
top5_clients_summary_df['Shipping (millions)'] = top5_clients_summary_df['Shipping (millions)'].apply(lambda x: '${:.2f}M'.format(x))
top5_clients_summary_df['Total Revenue (millions)'] = top5_clients_summary_df['Total Revenue (millions)'].apply(lambda x: '${:.2f}M'.format(x))
top5_clients_summary_df['Total Profit (millions)'] = top5_clients_summary_df['Total Profit (millions)'].apply(lambda x: '${:.2f}M'.format(x))

# Display the formatted DataFrame
top5_clients_summary_df


Client ID   Units Shipping (millions) Total Revenue (millions)  \
0      24741  239862              $5.13M                  $82.27M   
2      38378   73667              $3.43M                  $12.91M   
4      66037   43018              $1.40M                  $10.26M   
3      46820   75768              $1.60M                   $9.74M   
1      33615   64313              $1.83M                   $8.38M   

  Total Profit (millions)  
0                 $36.58M  
2                  $3.27M  
4                  $3.26M  
3                  $2.74M  
1                  $2.20M

The Top 5 clients are providing Total Revenue of $123.48 Million and Total Profit of $48.05 Million.  Client ID 24741 is far and away the most profitable client for the business and contribnuting 66.62% of the Total Revenue and 76.12% of the total profit for the Top 5 Clients.  It is imperative to make sure Client ID 24741 is top priority.
